name: Docker Image CI/CD for luvit

env:
  TARGET: luvit

on:
  push:
    branches: [ "main" ]
    paths:
      - 'luvit/**'
  pull_request:
    branches: [ "main" ]
  #schedule:
  #  - cron: '00 02 * * *'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build ${{ env.TARGET }} and push
      uses: docker/build-push-action@v6
      with:
        context: ./${{ env.TARGET }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.TARGET }}:latest
